fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      # linter
      - id: ruff
        args: [ --fix ]
      # formatter
      - id: ruff-format
