name: Test Workflow

on:
  #push:
  #  branches: [ main, develop ]
  #pull_request:
  #  branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: false
        type: boolean

jobs:
  install_dependencies:
    uses: ./.github/workflows/prepare_environment.yaml
    with:
      run_command: poetry install --no-root --with dev


  lint:
    needs: install_dependencies
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/prepare_environment.yaml
    with:
      run_command: poetry run ruff check


  test:
    needs: [ install_dependencies, lint ]
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.inputs.test == 'true')
    uses: ./.github/workflows/prepare_environment.yaml
    with:
      run_command: poetry run pytest