name: Test Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # workflow_dispatch:
  #   inputs:
  #     test:
  #       description: 'Run tests'
  #       required: false
  #       type: boolean

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/prepare_environment
      - name: Install dependencies
        run: poetry install --no-root --with dev


  lint:
    runs-on: ubuntu-latest
    needs: install_dependencies
    if: github.event_name == 'pull_request'
    steps:
      - uses: ./.github/actions/prepare_environment
      - name: Install dependencies
        run: poetry run ruff check


  test:
    runs-on: ubuntu-latest
    needs: [ install_dependencies, lint ]
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.inputs.test == 'true')
    steps:
      - uses: ./.github/actions/prepare_environment
      - name: Run tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: poetry run pytest