name: Test Workflow

env:
  ALLURE_RESULTS_PATH: allure-results
  ALLURE_REPORT_PATH: allure-report

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # workflow_dispatch:
  #   inputs:
  #     test:
  #       description: 'Run tests'
  #       required: false
  #       type: boolean

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-environment
      - name: Install dependencies
        run: poetry install --no-root --with dev


  lint:
    runs-on: ubuntu-latest
    needs: install_dependencies
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-environment
      - name: Run linter
        run: poetry run ruff check


  test:
    runs-on: ubuntu-latest
    needs: [ install_dependencies, lint ]
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.inputs.test == 'true')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-environment
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
        run: poetry run pytest --alluredir $ALLURE_RESULTS_PATH
      - name: Prepare Allure Report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        id: allure-report
        with:
          allure_results: $ALLURE_RESULTS_PATH
          allure_report: $ALLURE_REPORT_PATH
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: $ALLURE_RESULTS_PATH