name: Environment Preparation

on:
  workflow_call:
    inputs:
      run_command:
        required: true
        type: string

jobs:
  prepare_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '2.0.1'
      - name: Prepare cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Run command
        run: ${{ inputs.run_command }}